new: SimpleOverlay
cyperdark/osu-counters pull request #4
Opened 2024-05-08 10:37 UTC by HosizoraN

Gameplay:
![Screenshot 2024-05-08 16-56-10](https://github.com/cyperdark/osu-counters/assets/81794354/cd171226-6c2a-4a3e-9c12-5721486ddd69)

ResultScreen:
![Screenshot 2024-05-08 16-56-20](https://github.com/cyperdark/osu-counters/assets/81794354/3e388599-2a8c-4e8a-b496-5343212d9ccc)

CompatibleWith: tosu
Support All Mode! Customizable!

Other: i also added customization to my own keyoverlay

2024-05-15 16:17 UTC, cyperdark requested changes

2024-05-15 16:17 UTC, cyperdark commented on counters/SimpleOverlay by HosizoraN/index.js
> +socket.api_v2(({ play }) => {
Remove this

2024-05-15 16:17 UTC, cyperdark commented on counters/SimpleOverlay by HosizoraN/index.js
> +        const Folder = folders.beatmap.replace(/#/g, "%23").replace(/%/g, "%25").replace(/\\/g, "/").replace(/'/g, "%27").replace(/ /g, "%20");
you can use [encodeURI](https://developer.mozilla.org/ru/docs/Web/JavaScript/Reference/Global_Objects/encodeURI)

idk if it's working, but worth trying

2024-05-15 16:17 UTC, cyperdark commented on counters/SimpleOverlay by HosizoraN/settings.values.json
> +{"ModeID":"Mania","KeyEnable":true,"HideUI":false,"KeyColor":"#ffffff","keyPressedColor":"#ffd256","TextColor":"#ffffff","keyTextColor":"#ffffff","katuColor":"#ffffff","h100Color":"#ffffff","h50Color
remove this file

2024-05-15 16:17 UTC, cyperdark commented on counters/SimpleOverlay by HosizoraN/index.html
> +    <script src="js/reconnecting-websocket.min.js"></script>
not used anywhere

2024-05-16 02:31 UTC, HosizoraN commented on counters/SimpleOverlay by HosizoraN/index.js
> +        const Folder = folders.beatmap.replace(/#/g, "%23").replace(/%/g, "%25").replace(/\\/g, "/").replace(/'/g, "%27").replace(/ /g, "%20");
i did try that and only space (%20) doesn't removed so it didn't worked out

![image](https://github.com/cyperdark/osu-counters/assets/81794354/29e5c653-cb30-40ca-91af-f32cd7902f08)

2024-05-16 14:19 UTC, merged