New : pp counter
cyperdark/osu-counters pull request #6
Opened 2024-07-31 20:03 UTC by Inlayo

Photo : ![1](https://github.com/user-attachments/assets/7354db54-a06e-4b65-859b-ecbea4673a11)
Video : https://youtu.be/nyS-b5tggo8
CompatibleWith: all

2024-08-08 21:14 UTC, cyperdark requested changes

2024-08-08 21:14 UTC, cyperdark commented on counters/pp counter by Inlayo/js/index.js
> +let progress = document.getElementById("progress");
remove unused selectors

2024-08-08 21:14 UTC, cyperdark commented on counters/pp counter by Inlayo/js/index.js
> +    miss: new CountUp('miss', 0, 0, 0, 0.5, { decimalPlaces: 2, useEasing: true, useGrouping: false, separator: " ", decimal: "." }),
and remove unused here as well

2024-08-08 21:14 UTC, cyperdark commented on counters/pp counter by Inlayo/js/index.js
> +        animation.ifFcpp.update(data.gameplay.pp.fc)
here as well

2024-08-09 14:48 UTC, Inlayo reviewed
:D

2024-08-27 11:33 UTC, cyperdark requested changes

2024-08-27 11:33 UTC, cyperdark commented on counters/pp counter by Inlayo/js/index.js
> +  if (fullTime !== data.menu.bm.time.mp3) {
unused code

2024-08-27 11:33 UTC, cyperdark commented on counters/pp counter by Inlayo/js/index.js
> +  if (data.gameplay.hits[0] > 0 || data.gameplay.hits.sliderBreaks > 0) {
unused code

2024-08-27 11:33 UTC, cyperdark commented on counters/pp counter by Inlayo/js/index.js
> +  if (
unused code

2024-08-27 14:50 UTC, Inlayo reviewed
:D

2024-09-03 17:34 UTC, merged